name = "WildcardArrays"
uuid = "05d16eb0-506c-4fac-9187-f7ce7e253b09"
authors = ["Mykel Kochenderfer <mykel@stanford.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
Debugger = "0.7"
OrderedCollections = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
